version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-test-project"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-iuh70bg1ttoi"
s3_prefix = "sam-test-project"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
